# https://pub.dev/packages/pedantic_mono
# https://github.com/mono0926/pedantic_mono/blob/main/lib/analysis_options.yaml

include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "./lib/generated_plugin_registrant.dart"