name: nyanbuzz
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.17.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true

