name: nyanbuzz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  roggle: ^0.2.1+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
